import { useTranslation } from "react-i18next";

const kh = {
  "User": "អ្នកប្រើ",
  "Customer": "អតិថិជន",
  "Supplier": "អ្នកផ្គត់ផ្គង់",
  "Item": "ទំនិញ",
  "Product": "ផលិតផល",
  "Products": "ផលិតផល",
  "Raw Material": "វត្ថុធាតុដើម",
  "Raw Materials": "វត្ថុធាតុដើម",
  "Stock Type": "ប្រភេទស្តុក",
  "Start Date": "កាលបរិច្ឆេទចាប់ផ្តើម",
  "End Date": "កាលបរិច្ឆេទបញ្ចប់",
  "Loading...": "កំពុងផ្ទុក...",
  "Get Report": "ទាញយករបាយការណ៍",
  "Export Excel": "នាំចេញ Excel",
  "Print": "បោះពុម្ព",
  "Save as PDF": "រក្សាទុកជា PDF",
  "Reset": "កំណត់ឡើងវិញ",
  "No Report Generated": "មិនទាន់មានរបាយការណ៍",
  "Generating report...": "កំពុងបង្កើតរបាយការណ៍...",
  "All": "ទាំងអស់",
  "All Users": "អ្នកប្រើទាំងអស់",
  "All Customers": "អតិថិជនទាំងអស់",
  "All Suppliers": "អ្នកផ្គត់ផ្គង់ទាំងអស់",
  "All Supplier": "អ្នកផ្គត់ផ្គង់ទាំងអស់",
  "All Items": "ទំនិញទាំងអស់",
  "All Types": "ប្រភេទទាំងអស់",
  "All Raw Materials": "វត្ថុធាតុដើមទាំងអស់",
  "Start": "ចាប់ផ្តើម",
  "End": "បញ្ចប់",
  "Unknown": "មិនស្គាល់",
  "Total": "សរុប",
  "Balance": "សមតុល្យ",
  "Payment": "ការទូទាត់",
  "Paid": "បានបង់",
  "Date": "កាលបរិច្ឆេទ",
  "Phone": "ទូរស័ព្ទ",
  "Subtotal": "សរុបរង",
  "Delivery": "សេវាដឹកជញ្ជូន",
  "Stock Report": "របាយការណ៍ស្តុក",
  "Generate and export stock reports": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុក",
  "Use the filters above to generate a stock report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុក",
  "Stock Report By Raw Material": "របាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Generate and export stock reports by raw material": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Use the filters above to generate a stock report by raw material": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Stock Report By Item": "របាយការណ៍ស្តុកតាមទំនិញ",
  "Generate and export stock reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុកតាមទំនិញ",
  "Use the filters above to generate a stock report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុកតាមទំនិញ",
  "Stock Return": "ទំនិញបង្វិលចូល",
  "Stock In": "ទំនិញចូលស្តុក",
  "Stock Out": "ទំនិញចេញស្តុក",
  "Stock Waste": "ទំនិញខូចខាត",
  "Stock Sale": "ទំនិញលក់ចេញ",
  "Barcode": "បាកូដ",
  "Total Stock In: ": "ទំនិញចូលសរុប: ",
  "Sales Report": "របាយការណ៍ការលក់",
  "Generate and export sales reports": "បង្កើត និងនាំចេញរបាយការណ៍ការលក់",
  "Use the filters above to generate a sales report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការលក់",
  "Sales Report By Item": "របាយការណ៍ការលក់តាមទំនិញ",
  "Generate and export sales reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ការលក់តាមទំនិញ",
  "Use the filters above to generate a sales report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការលក់តាមទំនិញ",
  "Purchase Report": "របាយការណ៍ការទិញ",
  "Generate and export purchase reports by user": "បង្កើត និងនាំចេញរបាយការណ៍ការទិញតាមអ្នកប្រើ",
  "Use the filters above to generate a purchase report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការទិញ",
  "Purchase Report By Item": "របាយការណ៍ការទិញតាមទំនិញ",
  "Generate and export purchase reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ការទិញតាមទំនិញ",
  "Use the filters above to generate a purchase report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការទិញតាមទំនិញ",
  "Production Report": "របាយការណ៍ផលិតកម្ម",
  "Generate and export production reports": "បង្កើត និងនាំចេញរបាយការណ៍ផលិតកម្ម",
  "Use the filters above to generate a production report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្ម",
  "Production Report By Raw Material": "របាយការណ៍ផលិតកម្មតាមវត្ថុធាតុដើម",
  "Generate and export production cost by raw material": "បង្កើត និងនាំចេញថ្លៃដើមផលិតកម្មតាមវត្ថុធាតុដើម",
  "Use the filters above to generate a production report by raw material": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្មតាមវត្ថុធាតុដើម",
  "Production Report By Item": "របាយការណ៍ផលិតកម្មតាមទំនិញ",
  "Generate and export production cost by item": "បង្កើត និងនាំចេញថ្លៃដើមផលិតកម្មតាមទំនិញ",
  "Use the filters above to generate a production report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្មតាមទំនិញ",
  "Expense Report": "របាយការណ៍ចំណាយ",
  "Raw Material Stock Report": "របាយការណ៍ស្តុកវត្ថុធាតុដើម",
  "Expense No": "លេខវិក្កយបត្រចំណាយ",
  "Expense Date": "ថ្ងៃចំណាយ",
  "Expense Type": "ប្រភេទចំណាយ",
  "Expense By": "រៀបចំដោយ",
  "Total Expenses: ": "ចំណាយសរុប: ",
  "Account Receivables Report": "របាយការណ៍ប្រាក់ត្រូវទទួល",
  "Account Receivables (AR)": "ប្រាក់ត្រូវទទួល (AR)",
  "Account Payables (AP)": "ប្រាក់ត្រូវបង់ (AP)",
  "Inventory Payables": "ប្រាក់ត្រូវបង់ថ្លៃទំនិញ",
  "Net Balance": "សមតុល្យសុទ្ធ",
  "Daily balances within selected range": "សមតុល្យប្រចាំថ្ងៃក្នុងចន្លោះដែលបានជ្រើសរើស",
  "Financial Insights": "ការយល់ដឹងផ្នែកហិរញ្ញវត្ថុ",
  "Debt Status": "ស្ថានភាពបំណុល",
  "Cash Coverage": "លទ្ធភាពទូទាត់សាច់ប្រាក់",
  "Coverage below 1.0x means receivables do not cover current liabilities.": "កម្រិតទាបជាង ១.០ដង មានន័យថាប្រាក់ត្រូវទទួលមិនទាន់គ្រប់គ្រាន់សម្រាប់ទូទាត់បំណុលបច្ចុប្បន្នទេ។",
  "Receivables Coverage": "ការគ្របដណ្តប់នៃប្រាក់ត្រូវទទួល",
  "Net Position": "ទីតាំងសុទ្ធ",
  "Monitor receivables, payables, and liquidity trends": "តាមដានប្រាក់ត្រូវទទួល ប្រាក់ត្រូវបង់ និងនិន្នាការសន្ទនីយភាព",
  "Healthy": "សុខភាពល្អ",
  "Balanced": "សមតុល្យ",
  "Overleveraged": "បំណុលលើសលប់",
  "Total Debt (AP + INV)": "បំណុលសរុប (AP + INV)",
  "AR vs Total Debt": "AR ធៀបនឹង បំណុលសរុប",
  "Track customers, balances, and collections": "តាមដានអតិថិជន សមតុល្យ និងការប្រមូលប្រាក់",
  "Use the filters above to generate an account receivables report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ប្រាក់ត្រូវទទួល",
  "Account Payables Report": "របាយការណ៍ប្រាក់ត្រូវបង់",
  "Track suppliers, balances, and payment status": "តាមដានអ្នកផ្គត់ផ្គង់ សមតុល្យ និងស្ថានភាពបង់ប្រាក់",
  "Use the filters above to generate an account payables report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ប្រាក់ត្រូវបង់",
  "Debt Analysis Dashboard": "ផ្ទាំងវិភាគបំណុល",
  "Profit Analysis Summary": "សេចក្តីសង្ខេបវិភាគប្រាក់ចំណេញ",
  "Total Amount": "ចំនួនសរុប",
  "Total Paid": "បានបង់សរុប",
  "Total Balance": "សមតុល្យសរុប",
  "Supplier Tel": "លេខទូរស័ព្ទអ្នកផ្គត់ផ្គង់",
  "Total Receivable": "សរុបត្រូវទទួល",
  "Total Payable": "សរុបត្រូវបង់",
  "Total Received": "សរុបទទួលបាន",
  "Purchase No": "លេខវិក្កយបត្រទិញ",
  "Purchase Date": "ថ្ងៃទិញ",
  "Order No": "លេខវិក្កយបត្រលក់",
  "Customer Tel": "លេខទូរស័ព្ទអតិថិជន",
  "Created By": "អ្នកបង្កើត",
  "Item Code": "កូដទំនិញ",
  "Item Name": "ឈ្មោះទំនិញ",
  "Category": "ប្រភេទ",
  "Brand": "ម៉ាក",
  "Unit Price": "តម្លៃរាយ",
  "Total Price": "តម្លៃសរុប",
  "Discount": "បញ្ចុះតម្លៃ",
  "Total Quantity: ": "បរិមាណសរុប: ",
  "Total Sales: ": "ការលក់សរុប: ",
  "Total Orders: ": "ការបញ្ជាទិញសរុប: ",
  "Total Purchases: ": "ការទិញសរុប: ",
  "Total Items: ": "ទំនិញសរុប: ",
  "Total Amount: ": "ចំនួនសរុប: ",
  "Total Cost: ": "ថ្លៃដើមសរុប: ",
  "Total Productions: ": "ផលិតកម្មសរុប: ",
  "Cost Per Unit": "តម្លៃក្នុងមួយឯកតា",
  "Total Raw Cost": "ថ្លៃដើមវត្ថុធាតុដើមសរុប",
  "Conversion": "ការបំប្លែង",
  "Production Qty": "បរិមាណផលិត",
  "Production Total Cost": "ថ្លៃដើមផលិតសរុប",
  "Raw Code": "កូដវត្ថុធាតុដើម",
  "Production No": "លេខផលិតកម្ម",
  "Production Date": "ថ្ងៃផលិត",
  "Qty": "ចំនួន",
  "Total Production Cost: ": "ថ្លៃដើមផលិតកម្មសរុប: ",
  "Total Raw Materials: ": "វត្ថុធាតុដើមសរុប: ",
  "Total Stock Entries: ": "ចលនាស្តុកសរុប: ",
  "Stock No": "លេខចលនាស្តុក",
  "From Warehouse": "ពីឃ្លាំង",
  "To Warehouse": "ទៅឃ្លាំង",
  "Quantity": "បរិមាណ",
  "Remark": "សម្គាល់",
  "Item Type": "ប្រភេទមុខទំនិញ",
  "Tax Amount": "ចំនួនពន្ធ",
  "Shipping Fee": "សេវាដឹកជញ្ជូន",
  "Total Paid": "បានបង់សរុប",
  "Total Quantity: ": "បរិមាណសរុប: ",
  "Collected: ": "បានប្រមូល: ",
  "Receivable: ": "ត្រូវទទួល: ",
  "Payable: ": "ត្រូវបង់: ",
  "Date Range": "ចន្លោះកាលបរិច្ឆេទ",
  "Material Code": "កូដវត្ថុធាតុដើម",
  "Material Name": "ឈ្មោះវត្ថុធាតុដើម",
  "Primary Unit": "ឯកតាគោល",
  "Secondary Unit": "ឯកតាបន្ទាប់បន្សំ",
  "Material": "វត្ថុធាតុដើម",
  "All Materials": "វត្ថុធាតុដើមទាំងអស់",
  "Total Materials: ": "វត្ថុធាតុដើមសរុប: ",
  "Handled By": "អ្នករៀបចំ",
  "Total Purchase Cost": "តម្លៃទិញសរុប",
  "Total Used Cost": "តម្លៃប្រើប្រាស់សរុប",
  "Total Return Cost": "តម្លៃបង្វិលសរុប",
  "Total Waste Cost": "តម្លៃខូចខាតសរុប",
  "Total Out Cost": "តម្លៃចេញសរុប",
  "Calculate Cost": "តម្លៃគណនា",
  "Stock Flow Analysis (Qty vs Cost)": "ការវិភាគចលនាស្តុក (បរិមាណ និង តម្លៃ)",
  "Cost Contribution": "ចំណែកតម្លៃ",
  "Quantity Units": "ចំនួនឯកតា",
  "Cost Amount ($)": "ចំនួនទឹកប្រាក់ ($)",
  "In Cost": "តម្លៃចូល",
  "Used Cost": "តម្លៃប្រើប្រាស់",
  "Waste Cost": "តម្លៃខូចខាត",
  "Return Cost": "តម្លៃបង្វិល",
  "Out Cost": "តម្លៃចេញ",
  "In": "ចូល",
  "Out": "ចេញ",
  "Used": "ប្រើ",
  "Waste": "ខូច",
  "Return": "បង្វិល",
  "Profit Analysis": "វិភាគប្រាក់ចំណេញ",
  "Track profits and expenses": "តាមដានប្រាក់ចំណេញ និងការចំណាយ",
  "Refresh": "ធ្វើឱ្យស្រស់",
  "Total Revenue": "ប្រាក់ចំណូលសរុប",
  "Total Net Profit": "ប្រាក់ចំណេញសុទ្ធ",
  "Purchase Cost": "ថ្លៃដើមទិញចូល",
  "Operating Expense": "ចំណាយប្រតិបត្តិការ",
  "Monthly Profit": "ប្រាក់ចំណេញប្រចាំខែ",
  "Cost Proportions": "សមាមាត្រថ្លៃដើម",
  "Revenue": "ប្រាក់ចំណូល",
  "Profit": "ប្រាក់ចំណេញ",
  "Cost": "ថ្លៃដើម",
  "Margin": "រឹម",
  "Loading profit analysis data...": "កំពុងផ្ទុកទិន្នន័យវិភាគប្រាក់ចំណេញ...",
  "Used Material Cost": "ថ្លៃដើមទំនិញប្រើប្រាស់",
  "Return RTS": "Return RTS",
  "Net Profit": "ប្រាក់ចំណេញសុទ្ធ",
  "Revenue ($)": "ប្រាក់ចំណូល ($)",
  "Cost ($)": "ថ្លៃដើម ($)",
  "Profit ($)": "ប្រាក់ចំណេញ ($)",
  "Margin (%)": "រឹម (%)",
  "Income Statement": "របាយការណ៍លទ្ធផល",
  "For the period from": "សម្រាប់រយៈពេលចាប់ពី",
  "to": "ដល់",
  "Total Sales Revenue": "ចំណូលលក់សរុប",
  "Cost of Goods Sold": "ថ្លៃដើមទំនិញលក់",
  "Less: Waste Cost": "ដក: តម្លៃទំនិញខូចខាត",
  "Total Cost of Sales": "ថ្លៃដើមលក់សរុប",
  "Gross Profit": "ប្រាក់ចំណេញដុល",
  "Operating Expenses": "ចំណាយប្រតិបត្តិការ",
  "Net income after all expenses": "ប្រាក់ចំណេញសុទ្ធបន្ទាប់ពីចំណាយទាំងអស់",
  "Generated on": "បង្កើតនៅថ្ងៃ",
  "Authorized Signature": "ហត្ថលេខាដែលមានការអនុញ្ញាត",
};

export function useReportText() {
  const { i18n } = useTranslation();

  const rt = (text) => {
    if (i18n.language === "kh") {
      return kh[text] || text;
    }
    return text;
  };

  return { rt, language: i18n.language };
}
