import { useTranslation } from "react-i18next";

const kh = {
  "User": "អ្នកប្រើ",
  "Customer": "អតិថិជន",
  "Supplier": "អ្នកផ្គត់ផ្គង់",
  "Item": "ទំនិញ",
  "Product": "ផលិតផល",
  "Products": "ផលិតផល",
  "Raw Material": "វត្ថុធាតុដើម",
  "Raw Materials": "វត្ថុធាតុដើម",
  "Stock Type": "ប្រភេទស្តុក",
  "Start Date": "កាលបរិច្ឆេទចាប់ផ្តើម",
  "End Date": "កាលបរិច្ឆេទបញ្ចប់",
  "Loading...": "កំពុងផ្ទុក...",
  "Get Report": "ទាញយករបាយការណ៍",
  "Export Excel": "នាំចេញ Excel",
  "Print": "បោះពុម្ព",
  "Reset": "កំណត់ឡើងវិញ",
  "No Report Generated": "មិនទាន់មានរបាយការណ៍",
  "Generating report...": "កំពុងបង្កើតរបាយការណ៍...",
  "All": "ទាំងអស់",
  "All Users": "អ្នកប្រើទាំងអស់",
  "All Customers": "អតិថិជនទាំងអស់",
  "All Suppliers": "អ្នកផ្គត់ផ្គង់ទាំងអស់",
  "All Supplier": "អ្នកផ្គត់ផ្គង់ទាំងអស់",
  "All Items": "ទំនិញទាំងអស់",
  "All Types": "ប្រភេទទាំងអស់",
  "All Raw Materials": "វត្ថុធាតុដើមទាំងអស់",
  "Unknown": "មិនស្គាល់",
  "Total": "សរុប",
  "Balance": "សមតុល្យ",
  "Payment": "ការទូទាត់",
  "Paid": "បានបង់",
  "Date": "កាលបរិច្ឆេទ",
  "Stock Report": "របាយការណ៍ស្តុក",
  "Generate and export stock reports": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុក",
  "Use the filters above to generate a stock report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុក",
  "Stock Report By Raw Material": "របាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Generate and export stock reports by raw material": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Use the filters above to generate a stock report by raw material": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុកតាមវត្ថុធាតុដើម",
  "Stock Report By Item": "របាយការណ៍ស្តុកតាមទំនិញ",
  "Generate and export stock reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ស្តុកតាមទំនិញ",
  "Use the filters above to generate a stock report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ស្តុកតាមទំនិញ",
  "Sales Report": "របាយការណ៍ការលក់",
  "Generate and export sales reports": "បង្កើត និងនាំចេញរបាយការណ៍ការលក់",
  "Use the filters above to generate a sales report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការលក់",
  "Sales Report By Item": "របាយការណ៍ការលក់តាមទំនិញ",
  "Generate and export sales reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ការលក់តាមទំនិញ",
  "Use the filters above to generate a sales report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការលក់តាមទំនិញ",
  "Purchase Report": "របាយការណ៍ការទិញ",
  "Generate and export purchase reports by user": "បង្កើត និងនាំចេញរបាយការណ៍ការទិញតាមអ្នកប្រើ",
  "Use the filters above to generate a purchase report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការទិញ",
  "Purchase Report By Item": "របាយការណ៍ការទិញតាមទំនិញ",
  "Generate and export purchase reports by item": "បង្កើត និងនាំចេញរបាយការណ៍ការទិញតាមទំនិញ",
  "Use the filters above to generate a purchase report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ការទិញតាមទំនិញ",
  "Production Report": "របាយការណ៍ផលិតកម្ម",
  "Generate and export production reports": "បង្កើត និងនាំចេញរបាយការណ៍ផលិតកម្ម",
  "Use the filters above to generate a production report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្ម",
  "Production Report By Raw Material": "របាយការណ៍ផលិតកម្មតាមវត្ថុធាតុដើម",
  "Generate and export production cost by raw material": "បង្កើត និងនាំចេញថ្លៃដើមផលិតកម្មតាមវត្ថុធាតុដើម",
  "Use the filters above to generate a production report by raw material": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្មតាមវត្ថុធាតុដើម",
  "Production Report By Item": "របាយការណ៍ផលិតកម្មតាមទំនិញ",
  "Generate and export production cost by item": "បង្កើត និងនាំចេញថ្លៃដើមផលិតកម្មតាមទំនិញ",
  "Use the filters above to generate a production report by item": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ផលិតកម្មតាមទំនិញ",
  "Expense Report": "របាយការណ៍ចំណាយ",
  "Raw Material Stock Report": "របាយការណ៍ស្តុកវត្ថុធាតុដើម",
  "Account Receivables Report": "របាយការណ៍ប្រាក់ត្រូវទទួល",
  "Track customers, balances, and collections": "តាមដានអតិថិជន សមតុល្យ និងការប្រមូលប្រាក់",
  "Use the filters above to generate an account receivables report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ប្រាក់ត្រូវទទួល",
  "Account Payables Report": "របាយការណ៍ប្រាក់ត្រូវបង់",
  "Track suppliers, balances, and payment status": "តាមដានអ្នកផ្គត់ផ្គង់ សមតុល្យ និងស្ថានភាពបង់ប្រាក់",
  "Use the filters above to generate an account payables report": "ប្រើតម្រងខាងលើដើម្បីបង្កើតរបាយការណ៍ប្រាក់ត្រូវបង់",
  "Debt Analysis Dashboard": "ផ្ទាំងវិភាគបំណុល",
  "Profit Analysis Summary": "សេចក្តីសង្ខេបវិភាគប្រាក់ចំណេញ",
  "Total Amount": "ចំនួនសរុប",
  "Total Paid": "បានបង់សរុប",
  "Total Balance": "សមតុល្យសរុប",
  "Total Receivable": "សរុបត្រូវទទួល",
  "Total Payable": "សរុបត្រូវបង់",
  "Total Received": "សរុបទទួលបាន",
  "Total Orders: ": "ការបញ្ជាទិញសរុប: ",
  "Total Purchases: ": "ការទិញសរុប: ",
  "Total Items: ": "ទំនិញសរុប: ",
  "Total Amount: ": "ចំនួនសរុប: ",
  "Total Cost: ": "ថ្លៃដើមសរុប: ",
  "Total Production Cost: ": "ថ្លៃដើមផលិតកម្មសរុប: ",
  "Total Raw Materials: ": "វត្ថុធាតុដើមសរុប: ",
  "Total Stock Entries: ": "ចលនាស្តុកសរុប: ",
  "Total Quantity: ": "បរិមាណសរុប: ",
  "Collected: ": "បានប្រមូល: ",
  "Receivable: ": "ត្រូវទទួល: ",
  "Payable: ": "ត្រូវបង់: ",
  "Date Range": "ចន្លោះកាលបរិច្ឆេទ",
  "Material": "វត្ថុធាតុដើម",
  "All Materials": "វត្ថុធាតុដើមទាំងអស់",
  "Handled By": "អ្នករៀបចំ",
  "Total Purchase Cost": "តម្លៃទិញសរុប",
  "Total Used Cost": "តម្លៃប្រើប្រាស់សរុប",
  "Total Return Cost": "តម្លៃបង្វិលសរុប",
  "Total Waste Cost": "តម្លៃខូចខាតសរុប",
  "Total Out Cost": "តម្លៃចេញសរុប",
  "Calculate Cost": "តម្លៃគណនា",
  "Stock Flow Analysis (Qty vs Cost)": "ការវិភាគចលនាស្តុក (បរិមាណ និង តម្លៃ)",
  "Cost Contribution": "ចំណែកតម្លៃ",
  "Quantity Units": "ចំនួនឯកតា",
  "Cost Amount ($)": "ចំនួនទឹកប្រាក់ ($)",
  "In Cost": "តម្លៃចូល",
  "Used Cost": "តម្លៃប្រើប្រាស់",
  "Waste Cost": "តម្លៃខូចខាត",
  "Return Cost": "តម្លៃបង្វិល",
  "Out Cost": "តម្លៃចេញ",
  "In": "ចូល",
  "Out": "ចេញ",
  "Used": "ប្រើ",
  "Waste": "ខូច",
  "Return": "បង្វិល",
  "Profit Analysis": "វិភាគប្រាក់ចំណេញ",
  "Track profits and expenses": "តាមដានប្រាក់ចំណេញ និងការចំណាយ",
  "Refresh": "ធ្វើឱ្យស្រស់",
  "Total Revenue": "ប្រាក់ចំណូលសរុប",
  "Total Net Profit": "ប្រាក់ចំណេញសុទ្ធ",
  "Purchase Cost": "ថ្លៃដើមទិញចូល",
  "Operating Expense": "ចំណាយប្រតិបត្តិការ",
  "Monthly Profit": "ប្រាក់ចំណេញប្រចាំខែ",
  "Cost Proportions": "សមាមាត្រថ្លៃដើម",
  "Revenue": "ប្រាក់ចំណូល",
  "Profit": "ប្រាក់ចំណេញ",
  "Cost": "ថ្លៃដើម",
  "Margin": "រឹម",
  "Loading profit analysis data...": "កំពុងផ្ទុកទិន្នន័យវិភាគប្រាក់ចំណេញ...",
  "Used Material Cost": "ថ្លៃដើមទំនិញប្រើប្រាស់",
  "Return RTS": "Return RTS",
  "Net Profit": "ប្រាក់ចំណេញសុទ្ធ",
  "Revenue ($)": "ប្រាក់ចំណូល ($)",
  "Cost ($)": "ថ្លៃដើម ($)",
  "Profit ($)": "ប្រាក់ចំណេញ ($)",
  "Margin (%)": "រឹម (%)",
};

export function useReportText() {
  const { i18n } = useTranslation();

  const rt = (text) => {
    if (i18n.language === "kh") {
      return kh[text] || text;
    }
    return text;
  };

  return { rt, language: i18n.language };
}
