import { useTranslation } from "react-i18next";

const kh = {
  "Loading...": "កំពុងផ្ទុក...",
  "Syncing with database...": "កំពុងធ្វើសមកាលកម្មជាមួយមូលដ្ឋានទិន្នន័យ...",
  "Items": "ទំនិញ",
  "Import": "នាំចូល",
  "Add New": "បន្ថែមថ្មី",
  "Add Item": "បន្ថែមទំនិញ",
  "Search database by name, code or category...": "ស្វែងរកតាមឈ្មោះ កូដ ឬប្រភេទ...",
  "No results found matching your search": "មិនមានលទ្ធផលត្រូវនឹងការស្វែងរក",
  "Delete Item": "លុបទំនិញ",
  "This action is permanent. Are you sure?": "សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។ តើអ្នកប្រាកដទេ?",
  "Item deleted successfully": "លុបទំនិញបានជោគជ័យ",
  "Error deleting item": "មានបញ្ហាក្នុងការលុបទំនិញ",
  "total items found": "ទំនិញសរុបដែលបានរកឃើញ",
  "Showing": "បង្ហាញ",
  "to": "ដល់",
  "of": "នៃ",
  "items": "ទំនិញ",
  "Page": "ទំព័រ",
  "Product": "ផលិតផល",
  "Code": "កូដ",
  "Stock": "ស្តុក",
  "Price": "តម្លៃ",
  "Actions": "សកម្មភាព",
  "In Stock": "មានស្តុក",
  "Sold Out": "អស់ស្តុក",
  "Stock:": "ស្តុក:",
  "off": "បញ្ចុះ",
  "Import Items": "នាំចូលទំនិញ",
  "Import items from Excel file or use the template": "នាំចូលទំនិញពីឯកសារ Excel ឬប្រើគំរូ",
  "Upload Excel File": "ផ្ទុកឡើងឯកសារ Excel",
  ".xlsx, .xls, .csv files supported": "គាំទ្រឯកសារ .xlsx, .xls, .csv",
  "Download Template": "ទាញយកគំរូ",
  "Get sample Excel format": "ទទួលបានទម្រង់ Excel គំរូ",
  "Error": "កំហុស",
  "Imported Items": "ទំនិញដែលបាននាំចូល",
  "Save All": "រក្សាទុកទាំងអស់",
  "Cancel": "បោះបង់",
  "Edit All": "កែទាំងអស់",
  "Import All": "នាំចូលទាំងអស់",
  "No Items Imported": "មិនទាន់មានទំនិញនាំចូល",
  "Upload an Excel file or download the template to get started.": "ផ្ទុកឡើងឯកសារ Excel ឬទាញយកគំរូដើម្បីចាប់ផ្តើម។",
  "Item Name": "ឈ្មោះទំនិញ",
  "Wholesale Price": "តម្លៃលក់ដុំ",
  "Category": "ប្រភេទ",
  "Brand": "ម៉ាក",
  "Scale": "ឯកតា",
  "Attributes": "លក្ខណៈ",
  "Images": "រូបភាព",
  "Enter item name": "បញ្ចូលឈ្មោះទំនិញ",
  "Select Category": "ជ្រើសប្រភេទ",
  "Select Brand": "ជ្រើសម៉ាក",
  "Select Scale": "ជ្រើសឯកតា",
  "Delete": "លុប",
  "Save": "រក្សាទុក",
  "Edit": "កែប្រែ",
  "Item saved successfully!": "រក្សាទុកទំនិញបានជោគជ័យ!",
  "All changes saved successfully!": "រក្សាទុកការផ្លាស់ប្តូរទាំងអស់បានជោគជ័យ!",
  "Edit all mode cancelled": "បានបោះបង់របៀបកែទាំងអស់",
  "Template downloaded successfully!": "ទាញយកគំរូបានជោគជ័យ!",
  "No items to import!": "មិនមានទំនិញសម្រាប់នាំចូល!",
  "Items imported successfully!": "នាំចូលទំនិញបានជោគជ័យ!",
  "Import failed": "នាំចូលបរាជ័យ",
  "Import failed!": "នាំចូលបរាជ័យ!",
  "Attribute Name": "ឈ្មោះលក្ខណៈ",
  "Value": "តម្លៃ",
  "Add Attribute": "បន្ថែមលក្ខណៈ",
  "No attributes": "មិនមានលក្ខណៈ",
  "Text": "អក្សរ",
  "Number": "លេខ",
  "Select": "ជ្រើសរើស",
  "Checkbox": "ប្រអប់ធីក",
  "Date": "កាលបរិច្ឆេទ",
  "Remove attribute": "លុបលក្ខណៈ",
  "more": "បន្ថែម",
  "Please fill in all required fields for": "សូមបំពេញគ្រប់ចន្លោះចាំបាច់សម្រាប់",
  "item(s)": "ទំនិញ",
  "not found in system.": "មិនមាននៅក្នុងប្រព័ន្ធ។",
  "Are you sure you want to delete": "តើអ្នកប្រាកដថាចង់លុប",
  "Preview": "មើលជាមុន",
  "N/A": "គ្មាន",
  "Permanently Delete?": "លុបជាអចិន្ត្រៃយ៍?",
  "Item removed": "បានលុបទំនិញ",
  "Delete failed": "លុបបរាជ័យ",
  "Edit Product": "កែផលិតផល",
  "Retail Price": "តម្លៃលក់រាយ",
  "Active Listing": "កំពុងដាក់លក់",
  "Wholesale Rate": "អត្រាលក់ដុំ",
  "Min. Bulk": "បរិមាណអប្បបរមា",
  "Units Sold": "ចំនួនលក់",
  "Rating": "ការវាយតម្លៃ",
  "Discount": "បញ្ចុះតម្លៃ",
  "Technical Specifications": "លក្ខណៈបច្ចេកទេស",
  "Available Finishes": "ពណ៌ដែលមាន",
  "Size Selection": "ជម្រើសទំហំ",
  "Item Out of Stock": "ទំនិញអស់ស្តុក",
  "Units available in warehouse": "មាននៅក្នុងឃ្លាំង",
  "View Stock Logs": "មើលប្រវត្តិស្តុក",
  "By": "ដោយ",
  "In": "នៅក្នុង",
};

export function useItemText() {
  const { i18n } = useTranslation();
  const it = (text) => (i18n.language === "kh" ? kh[text] || text : text);
  return { it, language: i18n.language };
}
