import { useTranslation } from "react-i18next";

const kh = {
  "Please enter a brand name": "សូមបញ្ចូលឈ្មោះម៉ាក",
  "Brand created successfully": "បង្កើតម៉ាកបានជោគជ័យ",
  "An error occurred while creating the brand": "មានបញ្ហាក្នុងការបង្កើតម៉ាក",
  "Confirm Creation": "បញ្ជាក់ការបង្កើត",
  "Do you want to add": "តើអ្នកចង់បន្ថែម",
  "to your brand list?": "ទៅក្នុងបញ្ជីម៉ាករបស់អ្នកឬ?",
  "Confirm": "បញ្ជាក់",
  "Cancel": "បោះបង់",
  "New Brand": "ម៉ាកថ្មី",
  "Add a new manufacturer to your inventory": "បន្ថែមក្រុមហ៊ុនផលិតថ្មីទៅក្នុងសារពើភ័ណ្ឌ",
  "Brand Identity": "អត្តសញ្ញាណម៉ាក",
  "e.g. Nike, Apple, Samsung...": "ឧ. Nike, Apple, Samsung...",
  "Tip:": "គន្លឹះ:",
  "Ensure the brand name is unique to avoid duplicates in your reports.": "សូមធានាថាឈ្មោះម៉ាកមិនស្ទួន ដើម្បីជៀសវាងទិន្នន័យស្ទួនក្នុងរបាយការណ៍។",
  "Create Brand": "បង្កើតម៉ាក",
  "Brand name cannot be empty": "ឈ្មោះម៉ាកមិនអាចទទេបានទេ",
  "Brand updated successfully": "បានកែប្រែម៉ាកដោយជោគជ័យ",
  "Failed to update brand": "បរាជ័យក្នុងការកែប្រែម៉ាក",
  "Save Changes?": "រក្សាទុកការកែប្រែ?",
  "Are you sure you want to rename": "តើអ្នកប្រាកដថាចង់ប្ដូរឈ្មោះ",
  "to": "ទៅជា",
  "Save Changes": "រក្សាទុកការកែប្រែ",
  "Discard": "បោះបង់ចោល",
  "Edit Brand": "កែប្រែម៉ាក",
  "Update manufacturer details": "កែប្រែព័ត៌មានក្រុមហ៊ុនផលិត",
  "Brand Name": "ឈ្មោះម៉ាក",
  "Modified": "បានកែ",
  "Enter brand name...": "បញ្ចូលឈ្មោះម៉ាក...",
  "Original Name:": "ឈ្មោះដើម:",
  "This change will reflect across all products associated with this brand.": "ការកែប្រែនេះនឹងអនុវត្តលើផលិតផលទាំងអស់ដែលពាក់ព័ន្ធនឹងម៉ាកនេះ។",
  "Update Brand": "កែប្រែម៉ាក",
  "Please enter a category name": "សូមបញ្ចូលឈ្មោះប្រភេទ",
  "Category created successfully": "បង្កើតប្រភេទបានជោគជ័យ",
  "Failed to create category": "បរាជ័យក្នុងការបង្កើតប្រភេទ",
  "Confirm New Category": "បញ្ជាក់ប្រភេទថ្មី",
  "Do you want to create the": "តើអ្នកចង់បង្កើត",
  "category?": "ប្រភេទនេះឬ?",
  "Create Now": "បង្កើតឥឡូវ",
  "New Category": "ប្រភេទថ្មី",
  "Group your products for better organization": "រៀបចំផលិតផលរបស់អ្នកឲ្យកាន់តែល្អ",
  "Category Name": "ឈ្មោះប្រភេទ",
  "e.g. Electronics, Home Decor, Soft Drinks...": "ឧ. Electronics, Home Decor, Soft Drinks...",
  "Categories help filter your inventory and generate sales reports.": "ប្រភេទជួយតម្រងសារពើភ័ណ្ឌ និងបង្កើតរបាយការណ៍លក់។",
  "Create Category": "បង្កើតប្រភេទ",
  "Category name cannot be empty": "ឈ្មោះប្រភេទមិនអាចទទេបានទេ",
  "Category updated successfully": "បានកែប្រែប្រភេទដោយជោគជ័យ",
  "Failed to update category": "បរាជ័យក្នុងការកែប្រែប្រភេទ",
  "Confirm Update": "បញ្ជាក់ការកែប្រែ",
  "Yes, Update": "បាទ/ចាស កែប្រែ",
  "Edit Category": "កែប្រែប្រភេទ",
  "Modify category name and settings": "កែប្រែឈ្មោះ និងការកំណត់ប្រភេទ",
  "Pending Change": "កំពុងរង់ចាំការកែប្រែ",
  "Enter category name...": "បញ្ចូលឈ្មោះប្រភេទ...",
  "Changing this name will update the classification for all items currently under": "ការផ្លាស់ប្តូរឈ្មោះនេះនឹងកែប្រែការចាត់ថ្នាក់សម្រាប់ទំនិញទាំងអស់នៅក្រោម",
  "Please enter a scale name": "សូមបញ្ចូលឈ្មោះឯកតា",
  "Unit of measurement created": "បានបង្កើតឯកតារង្វាស់",
  "Failed to create scale": "បរាជ័យក្នុងការបង្កើតឯកតា",
  "Confirm New Unit": "បញ្ជាក់ឯកតាថ្មី",
  "Add": "បន្ថែម",
  "to your measurement units?": "ទៅក្នុងបញ្ជីឯកតារង្វាស់របស់អ្នកឬ?",
  "New Scale": "ឯកតាថ្មី",
  "Define units of measurement": "កំណត់ឯកតារង្វាស់",
  "Unit Name / Measurement": "ឈ្មោះឯកតា / រង្វាស់",
  "e.g. Kilograms (kg), Liters (L), Pieces (pcs)...": "ឧ. Kilograms (kg), Liters (L), Pieces (pcs)...",
  "Scales ensure accuracy in stock levels and pricing calculations.": "ឯកតាជួយធានាភាពត្រឹមត្រូវនៃស្តុក និងការគណនាតម្លៃ។",
  "Create Scale": "បង្កើតឯកតា",
  "Scale name cannot be empty": "ឈ្មោះឯកតាមិនអាចទទេបានទេ",
  "Unit updated successfully": "បានកែប្រែឯកតាដោយជោគជ័យ",
  "Failed to update scale": "បរាជ័យក្នុងការកែប្រែឯកតា",
  "Update Measurement Unit": "កែប្រែឯកតារង្វាស់",
  "Confirm changing unit name from": "បញ្ជាក់ការផ្លាស់ប្តូរឈ្មោះឯកតាពី",
  "Confirm Update": "បញ្ជាក់ការកែប្រែ",
  "Edit Scale": "កែប្រែឯកតា",
  "Update unit of measurement details": "កែប្រែព័ត៌មានឯកតារង្វាស់",
  "Unit Name / Symbol": "ឈ្មោះឯកតា / និមិត្តសញ្ញា",
  "EDITING": "កំពុងកែ",
  "e.g. Kilograms, Meters, Liters...": "ឧ. Kilograms, Meters, Liters...",
  "Previous value was": "តម្លៃមុនគឺ",
  "This will update all associated product measurements.": "វានឹងកែប្រែរង្វាស់ផលិតផលដែលពាក់ព័ន្ធទាំងអស់។",
  "Update Scale": "កែប្រែឯកតា",
  "Stock type created successfully": "បង្កើតប្រភេទស្តុកបានជោគជ័យ",
  "Failed to create stock type": "បរាជ័យក្នុងការបង្កើតប្រភេទស្តុក",
  "An error occurred while creating the stock type": "មានបញ្ហាក្នុងការបង្កើតប្រភេទស្តុក",
  "Question": "សំណួរ",
  "Are you sure you want create stock_type?": "តើអ្នកប្រាកដថាចង់បង្កើតប្រភេទស្តុកឬ?",
  "Ok": "យល់ព្រម",
  "Create stock type": "បង្កើតប្រភេទស្តុក",
  "Stock type name": "ឈ្មោះប្រភេទស្តុក",
  "Enter stock type name here. . .": "បញ្ចូលឈ្មោះប្រភេទស្តុកនៅទីនេះ...",
  "Close": "បិទ",
  "Stock type updated successfully": "បានកែប្រែប្រភេទស្តុកដោយជោគជ័យ",
  "Failed to update stock type": "បរាជ័យក្នុងការកែប្រែប្រភេទស្តុក",
  "An error occurred while updating the stock type": "មានបញ្ហាក្នុងការកែប្រែប្រភេទស្តុក",
  "Are you sure you want update stock_type?": "តើអ្នកប្រាកដថាចង់កែប្រែប្រភេទស្តុកឬ?",
  "Update StockType": "កែប្រែប្រភេទស្តុក",
  "StockType name": "ឈ្មោះប្រភេទស្តុក",
  "Enter stock_type name here. . .": "បញ្ចូលឈ្មោះប្រភេទស្តុកនៅទីនេះ...",
  "Submit": "ដាក់ស្នើ",
  "System record created": "បានបង្កើតកំណត់ត្រាប្រព័ន្ធ",
  "System error: Failed to initialize": "កំហុសប្រព័ន្ធ: បរាជ័យក្នុងការចាប់ផ្តើម",
  "System Confirmation": "ការបញ្ជាក់ប្រព័ន្ធ",
  "Are you sure you want to register": "តើអ្នកប្រាកដថាចង់ចុះឈ្មោះ",
  "Add New Storage Entity": "បន្ថែមឃ្លាំងថ្មី",
  "Entity Name:": "ឈ្មោះអង្គភាព:",
  "Enter identifier...": "បញ្ចូលលេខសម្គាល់...",
  "Operational Status:": "ស្ថានភាពប្រតិបត្តិការ:",
  "Stocked": "មានស្តុក",
  "Entity will be available for inventory indexing.": "អង្គភាពនេះនឹងអាចប្រើសម្រាប់សារពើភ័ណ្ឌ។",
  "Disabled": "បិទដំណើរការ",
  "Entity will be created but remain inactive.": "អង្គភាពនេះនឹងត្រូវបានបង្កើត ប៉ុន្តែមិនសកម្ម។",
  "Note: Changes to system entities may take a few moments to propagate across all nodes in the management cluster.": "ចំណាំ៖ ការផ្លាស់ប្តូរអង្គភាពប្រព័ន្ធអាចត្រូវការពេលបន្តិចដើម្បីធ្វើសមកាលកម្មទៅគ្រប់កន្លែង។",
  "Create Record": "បង្កើតកំណត់ត្រា",
  "System record updated": "បានកែប្រែកំណត់ត្រាប្រព័ន្ធ",
  "Update failed: System error": "បរាជ័យក្នុងការកែប្រែ: កំហុសប្រព័ន្ធ",
  "Confirm System Change": "បញ្ជាក់ការកែប្រែប្រព័ន្ធ",
  "Commit modifications to entity ID:": "អនុវត្តការកែប្រែទៅកាន់អង្គភាពលេខសម្គាល់៖",
  "Modify Facility Record": "កែប្រែកំណត់ត្រាឃ្លាំង",
  "Entity Name": "ឈ្មោះអង្គភាព",
  "Hub Status": "ស្ថានភាពឃ្លាំង",
  "Reference ID:": "លេខយោង៖",
  "Modifications will sync across the inventory cluster upon saving.": "ការកែប្រែនឹងធ្វើសមកាលកម្មទៅក្នុងប្រព័ន្ធស្តុកពេលរក្សាទុក។",
  "Commit Update": "អនុវត្តការកែប្រែ",
  "Expense category created successfully!": "បង្កើតប្រភេទចំណាយបានជោគជ័យ!",
  "Failed to create expense category": "បរាជ័យក្នុងការបង្កើតប្រភេទចំណាយ",
  "An error occurred while creating the expense category": "មានបញ្ហាក្នុងការបង្កើតប្រភេទចំណាយ",
  "Please enter a category name": "សូមបញ្ចូលឈ្មោះប្រភេទ",
  "Create New Expense Category": "បង្កើតប្រភេទចំណាយថ្មី",
  "Are you sure you want to create this expense category?": "តើអ្នកប្រាកដថាចង់បង្កើតប្រភេទចំណាយនេះឬ?",
  "Create": "បង្កើត",
  "Create Expense Type": "បង្កើតប្រភេទចំណាយ",
  "Add a new category to organize your expenses": "បន្ថែមប្រភេទថ្មីសម្រាប់រៀបចំចំណាយរបស់អ្នក",
  "Required Field": "ចន្លោះចាំបាច់",
  "Category Name": "ឈ្មោះប្រភេទ",
  "Enter category name (e.g., Office Supplies, Travel, Marketing)": "បញ្ចូលឈ្មោះប្រភេទ (ឧ. សម្ភារៈការិយាល័យ, ដំណើរ, ទីផ្សារ)",
  "Choose a descriptive name for easy identification": "ជ្រើសរើសឈ្មោះដែលងាយសម្គាល់",
  "Create Category": "បង្កើតប្រភេទ",
  "Please enter a category name to continue": "សូមបញ្ចូលឈ្មោះប្រភេទដើម្បីបន្ត",
  "Expanse type updated successfully": "បានកែប្រែប្រភេទចំណាយដោយជោគជ័យ",
  "Failed to update expense type": "បរាជ័យក្នុងការកែប្រែប្រភេទចំណាយ",
  "An error occurred while updating the expense_type": "មានបញ្ហាក្នុងការកែប្រែប្រភេទចំណាយ",
  "Are you sure you want update expense_type?": "តើអ្នកប្រាកដថាចង់កែប្រែប្រភេទចំណាយឬ?",
  "Update ExpanseType": "កែប្រែប្រភេទចំណាយ",
  "ExpanseType name": "ឈ្មោះប្រភេទចំណាយ",
  "Enter expense_type name here. . .": "បញ្ចូលឈ្មោះប្រភេទចំណាយនៅទីនេះ...",
  "System menu deployed": "បានបង្កើតម៉ឺនុយប្រព័ន្ធ",
  "System error: Link failed": "កំហុសប្រព័ន្ធ: បរាជ័យក្នុងការភ្ជាប់",
  "System Link Confirmation": "ការបញ្ជាក់តំណប្រព័ន្ធ",
  "Confirming creation of": "បញ្ជាក់ការបង្កើត",
  "routing entity?": "ធាតុបញ្ជូនផ្លូវឬ?",
  "Navigation Interface Architect": "អ្នកកំណត់រចនាសម្ព័ន្ធម៉ឺនុយ",
  "Menu Name": "ឈ្មោះម៉ឺនុយ",
  "Placement": "ទីតាំង",
  "Select System Layer": "ជ្រើសស្រទាប់ប្រព័ន្ធ",
  "Path (Route)": "ផ្លូវ (Route)",
  "Order Index": "លំដាប់",
  "Icon (Visual Identity)": "រូបតំណាង",
  "Preview": "មើលជាមុន",
  "REPLACE": "ជំនួស",
  "Upload SVG or PNG icon": "ផ្ទុកឡើងរូប SVG ឬ PNG",
  "Upload a high-resolution icon for the sidebar. Recommended size: 64x64px.": "ផ្ទុកឡើងរូបតំណាងគុណភាពខ្ពស់សម្រាប់របារចំហៀង។ ទំហំផ្ដល់អនុសាសន៍៖ 64x64px។",
  "Choose File": "ជ្រើសឯកសារ",
  "Initialize Menu": "បង្កើតម៉ឺនុយ",
  "System configuration updated": "បានកែប្រែការកំណត់ប្រព័ន្ធ",
  "Update failed": "បរាជ័យក្នុងការកែប្រែ",
  "Confirm Modification": "បញ្ជាក់ការកែប្រែ",
  "Save changes to the": "រក្សាទុកការកែប្រែទៅ",
  "navigation record?": "កំណត់ត្រាម៉ឺនុយឬ?",
  "menu": "ម៉ឺនុយ",
  "Update Routing Resource": "កែប្រែធនធានផ្លូវ",
  "Path (Route URI)": "ផ្លូវ (Route URI)",
  "Resource Icon": "រូបតំណាងធនធាន",
  "CHANGE": "ប្ដូរ",
  "Update Visual Asset": "កែប្រែរូបតំណាង",
  "Upload a new icon to replace the current system asset.": "ផ្ទុកឡើងរូបតំណាងថ្មីដើម្បីជំនួសរូបចាស់។",
  "Upload New": "ផ្ទុកឡើងថ្មី",
  "Save Record": "រក្សាទុកកំណត់ត្រា",
};

export function useViewText() {
  const { i18n } = useTranslation();
  const vt = (text) => (i18n.language === "kh" ? kh[text] || text : text);
  return { vt, language: i18n.language };
}
